CREATE TABLE `proposals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`salesPersonName` varchar(255) NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`productType` varchar(50) NOT NULL,
	`imobPlan` varchar(20),
	`locPlan` varchar(20),
	`imobUsers` int,
	`closings` int,
	`leads` int,
	`externalAI` int DEFAULT 0,
	`whatsapp` int DEFAULT 0,
	`imobVipSupport` int DEFAULT 0,
	`imobDedicatedCS` int DEFAULT 0,
	`contracts` int,
	`newContracts` int,
	`locVipSupport` int DEFAULT 0,
	`locDedicatedCS` int DEFAULT 0,
	`chargesBoleto` int DEFAULT 0,
	`boletoAmount` int,
	`chargesSplit` int DEFAULT 0,
	`splitAmount` int,
	`selectedAddons` text,
	`paymentPlan` varchar(20) NOT NULL,
	`totalMonthly` int NOT NULL,
	`totalAnnual` int NOT NULL,
	`implantationFee` int NOT NULL,
	`firstYearTotal` int NOT NULL,
	`postPaidTotal` int,
	`revenueFromBoletos` int,
	`revenueFromInsurance` int,
	`netGain` int,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `proposals_id` PRIMARY KEY(`id`)
);
