CREATE TABLE `clientRegistry` (
	`id` int AUTO_INCREMENT NOT NULL,
	`clientName` varchar(255) NOT NULL,
	`email` varchar(320),
	`agencyName` varchar(255),
	`cellPhone` varchar(50),
	`landlinePhone` varchar(50),
	`websiteUrl` text,
	`businessType` varchar(50),
	`firstQuoteId` int,
	`lastQuoteId` int,
	`totalQuotes` int NOT NULL DEFAULT 1,
	`firstVendorName` varchar(255),
	`lastVendorName` varchar(255),
	`firstVendorUserId` int,
	`lastVendorUserId` int,
	`lastProduct` varchar(20),
	`lastPlans` text,
	`lastKomboName` varchar(100),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`deletedAt` timestamp,
	CONSTRAINT `clientRegistry_id` PRIMARY KEY(`id`)
);
