/**
 * Lists of CRM and ERP systems for business nature section
 */

export const CRM_SYSTEMS = [
  "AGLET",
  "APOLAR SALES",
  "APRESENTA.ME",
  "ARBO (Exceto Arbo HUB)",
  "ATENDE TOTAL",
  "BEAGLE SHIP",
  "BETABIT",
  "BITRIX",
  "BOTLEADS",
  "C2S",
  "CASASOFT",
  "CIMO",
  "CONSTRUTOR DE VENDAS",
  "DOMMUS",
  "FACILITA (Apenas para incorporadoras)",
  "FLEXPRO",
  "FLIP",
  "FOSTER",
  "GESTÃO REAL",
  "HARRY",
  "HUBSPOT",
  "HUB.W",
  "IMOALERT",
  "IMOBEX/UNIVEN",
  "IMOBIBRASIL",
  "IMOBIFORCE",
  "IMOBZI",
  "IMOGESTÃO",
  "INFORCE",
  "IY2B",
  "JETIMOB",
  "KENLO LEADS",
  "KOMMO",
  "KUROLE",
  "LEADFY",
  "MIDAS",
  "MSYS-IMOB",
  "NIDO",
  "NONSTOP",
  "PAINEL IMOBILIARIO/STUDIO72",
  "PEPIN",
  "PRAEDIUM",
  "PROPERFY",
  "RAUZEE",
  "RD STATION CONVERSAS",
  "RD STATION MARKETING",
  "REALMATE",
  "ROBUST",
  "RUA-DOIS",
  "STUDIO72/PAINEL IMOBILIARIO",
  "SIGASOFT",
  "SISGER",
  "SI9",
  "SUPREMO",
  "SOBRESSAI",
  "SOHTEC",
  "SYSONE",
  "TECIMOB",
  "UNIVEN/IMOBEX",
  "UNIVERSAL (Imoview)",
  "VISTA",
  "VIA SW",
  "VOA CORRETOR",
  "WHATSAPP-SIMPLE",
  "WIDE-SYS",
  "ZENVIA",
  "Outro",
] as const;

export const ERP_SYSTEMS = [
  "Superlogica",
  "Wide-Sys",
  "CasaSoft",
  "Univen (Union)",
  "Nido",
  "Apresenta.me",
  "Outro",
] as const;

export type CRMSystem = typeof CRM_SYSTEMS[number];
export type ERPSystem = typeof ERP_SYSTEMS[number];
